// <auto-generated />
using Formula1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Formula1.Migrations
{
    [DbContext(typeof(Formula1Context))]
    partial class Formula1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Formula1.Models.Posicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeEquipe")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePiloto")
                        .HasColumnType("TEXT");

                    b.Property<string>("PontosCorrida")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosicaoGrid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posicao");
                });
#pragma warning restore 612, 618
        }
    }
}
